### ISSUE TITLE
Configure loader for .sass too?

### ISSUE THREAD

**Issue by insin** [insin/nwb-sass#1]
Should this configure loaders for `.scss` and `.sass`?

Currently it configures a `.scss` loader which gets a `sass` loader id, which feels a bit weird, but it seems(?) the `.sass` indented syntax is either looked down upon or considered legacy in some parts.

I've never used any CSS preprocessors before, so winging it here.

**Comment by slmgc** [comment]
Hi @insin 
It would be great if this loader could import .sass files too, because we use SASS syntax heavily for our project and it's not very convenient to convert all styles to SCSS syntax.

**Comment by insin** [comment]
Cool, if that's useful I'll make the next release support both
